/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import Controller.SongController;
import Model.Song;
import java.util.ArrayList;



/**
 *
 * @author airm2
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());
    
    // Table model for View Songs table
private final javax.swing.table.DefaultTableModel model;

// To track which row is being edited
private int editingRowIndex = -1;

//Controller instance(handels Curd+Storage)
private final SongController songController;
//List that holds all songs (loaded from file)
private ArrayList<Song> songs;

    
    
    

    /**
     * Creates new form AD
     */
    public AdminDashboard() {
        initComponents();
        MainPanel.add(DashboardPanel, "dashboard");
        MainPanel.add(ViewSongPanel, "view");
        MainPanel.add(AddSongPanel, "add");
        MainPanel.add(SearchSortPanel, "search");
        MainPanel.add(UserViewPanel, "user");
        model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        // Remove NetBeans dummy empty rows
model.setRowCount(0);

// Create controller and load data
songController = new SongController();
songs = songController.getAllSongs();

// If no data exists (first run), add default songs
if (songs.isEmpty()) {
    songController.addSong(new Song("Shape of You", "Ed Sheeran", "Divide", "Pop", 4, 2017));
    songController.addSong(new Song("Believer", "Imagine Dragons", "Evolve", "Rock", 3, 2018));
    songController.addSong(new Song("Fix You", "Coldplay", "X&Y", "Rock", 4, 2005));
    songController.addSong(new Song("Someone Like You", "Adele", "21", "Pop", 5, 2011));
    songController.addSong(new Song("Perfect", "Adele", "21", "Pop", 5, 2010));

    songs = songController.getAllSongs(); // reload after insert
}

// Load songs into JTable
loadSongsToTable();
        
        
        
        DashboardPanel.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createTitledBorder("Admin Overview"),
        javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
    )
);
        


    }
    /*
 * Loads songs from the model list into JTable
 * Called on startup and after add/update/delete
 */
private void loadSongsToTable() {
    model.setRowCount(0); // clear table first

    for (Song s : songs) {
        model.addRow(new Object[]{
            s.getTitle(),
            s.getArtist(),
            s.getAlbum(),
            s.getGenre(),
            s.getDuration(),
            s.getReleaseYear()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        DashboardPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ViewSongPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tableContainerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddSongPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtArtist = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAlbum = new javax.swing.JTextField();
        comboGenre = new javax.swing.JComboBox<>();
        txtDuration = new javax.swing.JTextField();
        txtReleaseYear = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtSongTitle = new javax.swing.JTextField();
        SearchSortPanel = new javax.swing.JPanel();
        UserViewPanel = new javax.swing.JPanel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(74, 74, 74));
        jPanel1.setPreferredSize(new java.awt.Dimension(663, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Music Management  System");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Panel ");

        jButton7.setBackground(new java.awt.Color(120, 120, 120));
        jButton7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("LOGOUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton7))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 360));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jButton1.setBackground(new java.awt.Color(70, 70, 70));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Dashboard");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(70, 70, 70));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Songs");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(70, 70, 70));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add Song");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(70, 70, 70));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Search & Sort");
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(70, 70, 70));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("User View");
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        DashboardPanel.setBackground(new java.awt.Color(240, 238, 232));

        jLabel4.setText("Dashboard");

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel4)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        MainPanel.add(DashboardPanel, "dashboard");

        ViewSongPanel.setBackground(java.awt.Color.darkGray);
        ViewSongPanel.setAutoscrolls(true);
        ViewSongPanel.setPreferredSize(new java.awt.Dimension(300, 450));
        ViewSongPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(235, 235, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(130, 120));

        jButton8.setBackground(new java.awt.Color(150, 150, 140));
        jButton8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton8.setText("Update Song");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(120, 120, 110), 1, true));
        jButton8.setOpaque(true);
        jButton8.setPreferredSize(new java.awt.Dimension(160, 45));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(150, 150, 140));
        jButton9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton9.setText("Delete Song");
        jButton9.setAutoscrolls(true);
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(120, 120, 110), 1, true));
        jButton9.setOpaque(true);
        jButton9.setPreferredSize(new java.awt.Dimension(160, 45));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        ViewSongPanel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(110, 110, 110));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Songs");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel3)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        ViewSongPanel.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tableContainerPanel.setBackground(java.awt.Color.darkGray);
        tableContainerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(70, 70, 70));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 50));

        jTable1.setBackground(java.awt.Color.darkGray);
        jTable1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Song Title", "Artist", "Album", "Genre", "Duration", "Release Year"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(java.awt.Color.lightGray);
        jTable1.setRowHeight(32);
        jTable1.setSelectionBackground(new java.awt.Color(120, 120, 120));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        tableContainerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        ViewSongPanel.add(tableContainerPanel, java.awt.BorderLayout.CENTER);

        MainPanel.add(ViewSongPanel, "view");

        AddSongPanel.setBackground(new java.awt.Color(58, 63, 63));
        AddSongPanel.setForeground(new java.awt.Color(240, 240, 240));
        AddSongPanel.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Song");

        jLabel7.setBackground(new java.awt.Color(240, 240, 240));
        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(220, 220, 220));
        jLabel7.setText("Song Title: ");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(220, 220, 220));
        jLabel8.setText("Artist:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(220, 220, 220));
        jLabel9.setText("Album:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(220, 220, 220));
        jLabel10.setText("Genre:");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Duration:");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(220, 220, 220));
        jLabel12.setText("Release Year:");
        jLabel12.setInheritsPopupMenu(false);

        comboGenre.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        comboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Genre", "Pop", "Rock", "Classical", "Jazz" }));
        comboGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenreActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(45, 52, 54));
        jButton6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(220, 220, 220));
        jButton6.setText("ADD SONG");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 8, 16));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(95, 95, 95));
        btnClear.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(220, 220, 220));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddSongPanelLayout = new javax.swing.GroupLayout(AddSongPanel);
        AddSongPanel.setLayout(AddSongPanelLayout);
        AddSongPanelLayout.setHorizontalGroup(
            AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSongPanelLayout.createSequentialGroup()
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSongPanelLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel5))
                    .addGroup(AddSongPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddSongPanelLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(66, 66, 66)
                                .addComponent(btnClear))
                            .addGroup(AddSongPanelLayout.createSequentialGroup()
                                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddSongPanelLayout.createSequentialGroup()
                                        .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSongPanelLayout.createSequentialGroup()
                                        .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)))
                                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAlbum)
                                    .addComponent(txtArtist)
                                    .addComponent(txtDuration)
                                    .addComponent(txtReleaseYear)
                                    .addComponent(txtSongTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(comboGenre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        AddSongPanelLayout.setVerticalGroup(
            AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSongPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSongTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReleaseYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(AddSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(btnClear))
                .addGap(32, 32, 32))
        );

        MainPanel.add(AddSongPanel, "add");

        javax.swing.GroupLayout SearchSortPanelLayout = new javax.swing.GroupLayout(SearchSortPanel);
        SearchSortPanel.setLayout(SearchSortPanelLayout);
        SearchSortPanelLayout.setHorizontalGroup(
            SearchSortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        SearchSortPanelLayout.setVerticalGroup(
            SearchSortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        MainPanel.add(SearchSortPanel, "search");

        javax.swing.GroupLayout UserViewPanelLayout = new javax.swing.GroupLayout(UserViewPanel);
        UserViewPanel.setLayout(UserViewPanelLayout);
        UserViewPanelLayout.setHorizontalGroup(
            UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        UserViewPanelLayout.setVerticalGroup(
            UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        MainPanel.add(UserViewPanel, "user");

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) MainPanel.getLayout();
            cl.show(MainPanel, "dashboard");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) MainPanel.getLayout();
            cl.show(MainPanel, "view");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) MainPanel.getLayout();
            cl.show(MainPanel, "add");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) MainPanel.getLayout();
            cl.show(MainPanel, "search");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) MainPanel.getLayout();
            cl.show(MainPanel, "user");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGenreActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        

    // --------- 1. READ INPUTS ----------
    String title = txtSongTitle.getText().trim();
    String artist = txtArtist.getText().trim();
    String album = txtAlbum.getText().trim();
    String genre = comboGenre.getSelectedItem().toString();
    String durationText = txtDuration.getText().trim();
    String yearText = txtReleaseYear.getText().trim();

    // --------- 2. VALIDATION ----------
    if (title.isEmpty() || artist.isEmpty() || album.isEmpty()
            || durationText.isEmpty() || yearText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "All fields must be filled.",
                "Input Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    if (genre.equals("Select Genre")) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a genre.",
                "Input Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    int duration, releaseYear;

    try {
        duration = Integer.parseInt(durationText);
        releaseYear = Integer.parseInt(yearText);

        if (duration <= 0 || releaseYear < 1900 || releaseYear > 2025) {
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid duration or release year.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
                this,
                "Duration and Release Year must be numeric.",
                "Input Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // --------- 3. UPDATE MODE ----------
    if (editingRowIndex != -1) {

        model.setValueAt(title, editingRowIndex, 0);
        model.setValueAt(artist, editingRowIndex, 1);
        model.setValueAt(album, editingRowIndex, 2);
        model.setValueAt(genre, editingRowIndex, 3);
        model.setValueAt(duration, editingRowIndex, 4);
        model.setValueAt(releaseYear, editingRowIndex, 5);

        editingRowIndex = -1; // exit edit mode

        JOptionPane.showMessageDialog(
                this,
                "Song updated successfully!",
                "Update",
                JOptionPane.INFORMATION_MESSAGE
        );

    } 
    // --------- 4. ADD MODE ----------
    else {
        Song song = new Song(
        title,
        artist,
        album,
        genre,
        duration,
        releaseYear
);

// ADD MODE
if (editingRowIndex == -1) {
    songController.addSong(song);
}
// UPDATE MODE
else {
    songController.updateSong(editingRowIndex, song);
    editingRowIndex = -1;
}

// Reload data from file/model
songs = songController.getAllSongs();
loadSongsToTable();

JOptionPane.showMessageDialog(
        this,
        "Song saved successfully!",
        "Success",
        JOptionPane.INFORMATION_MESSAGE
);


        
    }

    // --------- 5. CLEANUP ----------
    btnClearActionPerformed(evt);

    CardLayout cl = (CardLayout) MainPanel.getLayout();
    cl.show(MainPanel, "view");


        
       

    
    
    


        
    


    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        

    // Clear the Song Title input field
    txtSongTitle.setText("");

    // Clear the Artist input field
    txtArtist.setText("");

    // Clear the Album input field
    txtAlbum.setText("");

    // Clear the Duration input field
    txtDuration.setText("");

    // Clear the Release Year input field
    txtReleaseYear.setText("");

    // Reset the Genre combo box to the default option
    // Index 0 represents "Select Genre"
    comboGenre.setSelectedIndex(0);

    // Set cursor focus back to the Song Title field
    // This improves usability for entering a new song
    txtSongTitle.requestFocus();


    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
    // 1. Get selected row from View Songs table
    int selectedRow = jTable1.getSelectedRow();

    // 2. If no row selected, show warning
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Please select a song to update.",
            "No Selection",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // 3. Store selected row index for update
    editingRowIndex = selectedRow;

    // 4. Read values from selected row
    txtSongTitle.setText(model.getValueAt(selectedRow, 0).toString());
    txtArtist.setText(model.getValueAt(selectedRow, 1).toString());
    txtAlbum.setText(model.getValueAt(selectedRow, 2).toString());
    comboGenre.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
    txtDuration.setText(model.getValueAt(selectedRow, 4).toString());
    txtReleaseYear.setText(model.getValueAt(selectedRow, 5).toString());

    // 5. Switch to Add Song panel
    CardLayout cl = (CardLayout) MainPanel.getLayout();
    cl.show(MainPanel, "add");

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(
            this,
            "Please select a song to delete.",
            "No Selection",
            JOptionPane.WARNING_MESSAGE
    );
    return;
}

int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this song?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {

    songController.deleteSong(selectedRow);

    songs = songController.getAllSongs();
    loadSongsToTable();

    JOptionPane.showMessageDialog(
            this,
            "Song deleted successfully.",
            "Deleted",
            JOptionPane.INFORMATION_MESSAGE
    );
}

        
        

        

    

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }
    // This method clears all input fields in the Add Song form
        private void clearFields() {
        txtSongTitle.setText("");
        txtArtist.setText("");
        txtAlbum.setText("");
        txtDuration.setText("");
        txtReleaseYear.setText("");
        comboGenre.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddSongPanel;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SearchSortPanel;
    private javax.swing.JPanel UserViewPanel;
    private javax.swing.JPanel ViewSongPanel;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> comboGenre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel tableContainerPanel;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtArtist;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtReleaseYear;
    private javax.swing.JTextField txtSongTitle;
    // End of variables declaration//GEN-END:variables
}
